groups/ceu-infrastructure/profiles/heritage-development-eu-west-2/vars
groups/ceu-infrastructure/profiles/heritage-live-eu-west-2/vars
groups/ceu-infrastructure/profiles/heritage-staging-eu-west-2/vars
groups/ceu-infrastructure/rds.tf
groups/ceu-infrastructure/variables.tf

Adding minor_version option into code and setting false for staging and live

Adding minor_version option into code and setting false for staging and live

---

groups/ceu-infrastructure/profiles/heritage-development-eu-west-2/vars
groups/ceu-infrastructure/profiles/heritage-live-eu-west-2/vars
groups/ceu-infrastructure/profiles/heritage-staging-eu-west-2/vars
groups/ceu-infrastructure/rds.tf
groups/ceu-infrastructure/variables.tf

Setup RDS Logging for DBA requirements and maintenance window control

RDS Logging for DBA requirements and maintenance window control

---

groups/ceu-infrastructure/profiles/heritage-development-eu-west-2/vars
groups/ceu-infrastructure/profiles/heritage-live-eu-west-2/vars
groups/ceu-infrastructure/profiles/heritage-staging-eu-west-2/vars
groups/ceu-infrastructure/rds.tf

Adding timezone change to CEU RDS instances in Development and Staging, also updating minor version in line with automatic updates

Adding timezone change to CEU RDS instances in Development and Staging

---

groups/ceu-infrastructure/asg_backend.tf
groups/ceu-infrastructure/data.tf
groups/ceu-infrastructure/iam.tf
groups/ceu-infrastructure/keys.tf
groups/ceu-infrastructure/locals.tf
groups/ceu-infrastructure/profiles/heritage-development-eu-west-2/vars
groups/ceu-infrastructure/profiles/heritage-live-eu-west-2/vars
groups/ceu-infrastructure/profiles/heritage-staging-eu-west-2/vars
groups/ceu-infrastructure/templates/bep_user_data.tpl
groups/ceu-infrastructure/variables.tf

Updated TF to deploy CEU BEP from existing AMI 
Based on existing work performed on EWF BEP
BACKEND data commented during initial testing in Dev
Empty cron data used during initial testing in Dev

Deploy CEU BEP

---

groups/ceu-infrastructure/iam.tf
groups/ceu-infrastructure/main.tf
groups/ceu-infrastructure/profiles/heritage-staging-eu-west-2/vars
groups/ceu-infrastructure/variables.tf
groups/ceu-infrastructure/vault-providers/approle
groups/ceu-infrastructure/vault-providers/token
groups/ceu-infrastructure/vault-providers/userpass
groups/ceu-infrastructure/vault.tf

Added vault-providers config to enable future migration to roles-based auth
Replaced release and config bucket names with vault-sourced data
Set ASG size to 1 in Staging

Add Vault providers and set ASG size to 1 in Staging

---

groups/ceu-infrastructure/data.tf
groups/ceu-infrastructure/locals.tf

Enabled use of vault-sourced backend data for BEP

Enable BEP Backend Config

---

groups/ceu-infrastructure/profiles/heritage-live-eu-west-2/vars
groups/ceu-infrastructure/profiles/heritage-staging-eu-west-2/vars

Update RDS Maintenance Window

---

groups/ceu-infrastructure/profiles/heritage-development-eu-west-2/vars
groups/ceu-infrastructure/profiles/heritage-staging-eu-west-2/vars

Bumped RDS minor version to match deployed infrastructure

---

groups/ceu-infrastructure/data.tf
groups/ceu-infrastructure/rds.tf

Added data source for CEU BEP security group
Added CEU BEP security group ID for RDS access

Allow RDS access to CEU BEP

---

groups/ceu-infrastructure/profiles/heritage-live-eu-west-2/vars

Updated live vars for upcoming minor version update

Bumped minor RDS version for Live

---

groups/ceu-infrastructure/profiles/heritage-development-eu-west-2/vars
groups/ceu-infrastructure/profiles/heritage-staging-eu-west-2/vars

Added dev CVO mount configuration
Added staging on-prem mount configuration

Add NFS Mount Configuration

---

groups/ceu-infrastructure/profiles/heritage-staging-eu-west-2/vars

Added CVO mount config for Staging

Add NFS Mounts

---

groups/ceu-infrastructure/data.tf
groups/ceu-infrastructure/templates/bep_user_data.tpl

Updated userdata to use updated templating syntax for nagios script
Added required template variable

Update nagios configuration

---

groups/ceu-infrastructure/profiles/heritage-staging-eu-west-2/vars

Bumped RDS minor version in staging to match deployed resources

Bump staging RDS minor version

---

groups/ceu-infrastructure/asg_backend.tf
groups/ceu-infrastructure/nlb_backend.tf
groups/ceu-infrastructure/outputs.tf
groups/ceu-infrastructure/route53.tf
groups/ceu-infrastructure/templates/heritage-staging-eu-west-2/bep_cron.tpl

Updated Staging cron
Added NLB resources for CUPS UI access
Added SG rules to permit CUPS UI access and for ELB healthchecks

BEP Cron updates & NLB config for CUPS UI access

---

groups/ceu-frontend/locals.tf

Changing environment local to heritage_environment local input as envronment is a reserved variable in Ansible

Changing environment local to heritage_environment local input as envronment is a reserved variable in Ansible

---

groups/ceu-frontend/README.md
groups/ceu-frontend/alb-internal.tf
groups/ceu-frontend/asg_frontend.tf
groups/ceu-frontend/locals.tf
groups/ceu-frontend/profiles/pci-services-eu-west-2 copy/vars
groups/ceu-frontend/profiles/pci-services-eu-west-2/vars
groups/ceu-frontend/sns.tf
groups/ceu-infrastructure/README.md
groups/ceu-infrastructure/data.tf

Users will be able to subscribe to SNS topic for alerts from the CEU Frontend service ALB and ASG Alarms.
Future alarms will also publish to this specific SNS topic.
** Only CEU resources should use this topic  for notifications **

ALB and ASG Alarm modules for CEU Frontend and SNS for Alarm actions

---

groups/ceu-frontend/README.md
groups/ceu-frontend/alb-internal.tf
groups/ceu-frontend/asg_frontend.tf

Updating module version and adding unhealthy host input with sensible number

Updating module version and adding unhealthy host input with sensible number

---

groups/ceu-infrastructure/locals.tf

Updated conditional for `ceu_fe_secgroup_rds_rule` local var to resolve a syntax issue.

Update ceu_fe_secgroup_rds_rule conditional

---

groups/ceu-infrastructure/data.tf
groups/ceu-infrastructure/locals.tf
groups/ceu-infrastructure/rds.tf

Converting security group rule to cidrs as cross account rules do not  work with Transit Gateway

Converting security group rule to cidrs as cross account rules do not  work with Transit Gateway

---

groups/ceu-frontend/README.md
groups/ceu-frontend/alb-internal.tf
groups/ceu-frontend/asg_frontend.tf
groups/ceu-frontend/sns.tf

Updating alarm modules to latest version, adding SNS topic for xMatters and updating existing SNS topic name

---

groups/ceu-infrastructure/profiles/heritage-development-eu-west-2/vars
groups/ceu-infrastructure/profiles/heritage-live-eu-west-2/vars
groups/ceu-infrastructure/profiles/heritage-staging-eu-west-2/vars

Upgraded Staging RDS to Oracle 19
Updated Dev RDS vars to bump RDS minor version
Updated Live RDS vars to bump RDS minor version

Upgrade Staging RDS to Oracle 19

---

groups/ceu-infrastructure/data.tf
groups/ceu-infrastructure/rds.tf

Added new data source to obtain CHD BEP security group
Updated RDS security group to permit access from CHD BEP

Permit RDS Access for CHD BEP

---

groups/ceu-frontend/alb-internal.tf
groups/ceu-frontend/data.tf
groups/ceu-frontend/locals.tf
groups/ceu-frontend/profiles/pci-services-eu-west-2/vars
groups/ceu-frontend/variables.tf

Added data source to retrieve ALB subnet mappings
Added local var to build up the `subnet_mapping` list as required by the ALB module
Added `subnet_mapping` parameter to ALB module
Added bool var to control which accounts use a static IP ALB configuration
Partially Resolves: CM-876

Set Static IPs for PCI Services ALB

---

groups/ceu-frontend/nlb_internal.tf

Removed security group from NLB as it's not supported

Remove NLB Security Group

---

groups/ceu-infrastructure/profiles/heritage-development-eu-west-2/vars

Updated parameters to upgrade CEU Dev to Oracle 19

Upgrade Dev RDS to Oracle 19

---

groups/ceu-infrastructure/profiles/heritage-live-eu-west-2/vars
groups/ceu-infrastructure/rds.tf

Updated parameters to upgrade Live RDS to Oracle 19

Upgrade Live RDS to Oracle 19

---

groups/ceu-infrastructure/profiles/heritage-live-eu-west-2/vars

Set `alarm_actions_enabled` to `true` in Live
Resolves: CM-1406

Enable Oracle alarm actions in live

---

groups/ceu-infrastructure/profiles/heritage-live-eu-west-2/vars

Updated live parameters to
* Remove JVM option
* Disable auto minor version upgrades

Remove JVM option, disable auto upgrades

---

groups/ceu-infrastructure/locals.tf
groups/ceu-infrastructure/rds.tf

Added vault lookup for chips-dba-dev instance

chips-dba-dev-cidrs
